# Generated by Django 4.1.6 on 2023-02-06 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0015_remove_resume_user_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
